<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<span class="badge badge-danger">YES</span>' => '<span class="badge badge-danger">DA</span>',
    '<span class="badge badge-success">NO</span>' => '<span class="badge badge-success">NU</span>',
    'Activate' => 'Activează',
    'Added By' => 'Adăugat De',
    'Added' => 'Adăugat',
    'All' => 'Toate',
    'An error occurred while saving the street' => 'A apărut o eroare la salvarea străzii',
    'An error occurred while saving the address' => 'A apărut o eroare la salvarea adresei',
    'Are you sure you want to activate this {item}?' => 'Ești sigur că vrei să activezi acest/această {item}?',
    'Are you sure you want to {action} this {item}?' => 'Ești sigur că vrei să {action} acest/această {item}?',
    'Cities' => 'Orașe',
    'City field' => 'Câmpul oraș',
    'city' => 'oraș',
    'Code' => 'Cod',
    'Counties' => 'Județe',
    'Countries' => 'Țări',
    'Country Code' => 'Cod țară',
    'Country field' => 'Câmpul țară',
    'Country ID' => '',
    'Country' => 'Țară',
    'country' => 'țară',
    'County Code' => 'Cod județ',
    'County' => 'Județ',
    'county' => 'județ',
    'Deleted' => 'Șters',
    'First page' => 'Prima pagină',
    'ID' => 'ID',
    'Id' => 'Id',
    'Last page' => 'Ultima pagină',
    'level' => 'nivel',
    'Name field' => 'Câmpul nume',
    'Name' => 'Nume',
    'Number field' => 'Câmpul număr',
    'Records per page' => 'Înregistrări pe pagină',
    'Select employee' => 'Selectează angajatul',
    'State Code' => '',
    'State field' => 'Câmpul județ',
    'State ID' => '',
    'Successfully activated!' => 'Activarea a fost realizată cu succes!',
    'Successfully deleted!' => 'Ștergerea a fost realizată cu succes!',
    'The requested page does not exist.' => 'Pagina nu există.',
    'Updated By' => 'Modificat De',
    'Updated' => 'Modificat',
    'View more details' => 'Vezi mai multe detalii',
    '{icon} Activate' => '{icon} Activează',
    '{icon} Back' => '{icon} Înapoi',
];
