<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Action Sql' => 'Acțiune sql',
    'Added By' => 'Adăugat de',
    'Added' => 'Adăugat',
    'After validating the entity does not have operations' => 'Entitate nu are operațiuni de executat după validare',
    'Check' => 'Verifică',
    'Code' => 'Cod',
    'Condition Sql' => 'Condiție sql',
    'Default value' => 'Valoarea ',
    'Deleted' => 'Șters',
    'Description' => 'Descriere',
    'Domain ID' => 'ID domeniu',
    'Domain' => 'Domeniu',
    'Entity Action ID' => 'ID actiune entitate',
    'Entity Change ID' => 'ID entitate modificată',
    'Entity ID' => 'ID entitate',
    'Entity Operation ID' => 'ID operatie entitate',
    'Entity' => 'Entitate',
    'Failed to update' => 'Actualizarea nu a putut fi realizată',
    'filter' => 'filtrează',
    'History find&replace' => 'Istoric găsiți și înlocuiți',
    'ID' => 'ID',
    'Name Column Change' => 'Nume coloana modificare',
    'Name Column Source' => 'Nume coloana sursă',
    'Name entity' => 'Nume entitate',
    'Name' => 'Nume',
    'New code' => 'Cod nou',
    'New entity or old entities are not set' => 'Valorile pentru înlocuire nu au fost setate',
    'New entity' => 'Nou',
    'New value' => 'Noua valoare',
    'Old code' => 'Cod vechi',
    'Old entities' => 'Vechi',
    'Old value' => 'Vechea valoare',
    'Order By' => 'Ordine',
    'Replace' => 'Găsiți și înlocuiți',
    'Replaced with success' => 'Găsirea și înlocuirea s-a executat cu succes',
    'Select all' => 'Selectează tot',
    'Select domain' => 'Selectează domeniu',
    'Select entity' => 'Selectează entitatea',
    'Select new entity' => 'Selectează entitate noua',
    'Select old entities' => 'Selectează entitatile vechi',
    'Select speciality' => 'Selectează specialitate',
    'Speciality' => 'Specialitate',
    'Status' => 'Status',
    'The data will be lost. Are you sure you want to leave?' => 'Datele vor fi pierdute. Ești sigur că dorești să părăsești pagina?',
    'The data will be lost. Are you sure you want to reload?' => 'Datele vor fi pierdute. Ești sigur că dorești să reîncarci pagina?',
    'The entity does not have operations' => 'Entitate nu are operațiuni de executat',
    'The entity does not have primary_key' => 'Entitate nu are cheie primară',
    'The requested entity does not exist' => 'Entitatea nu există',
    'Unselect all' => 'Deselectează tot',
    'Updated By' => 'Modificat de',
    'Updated' => 'Modificat',
];