ALTER TABLE `user`
    ADD `psw_changed` TINYINT NOT NULL DEFAULT '0' COMMENT 'used to verify if the user changed the default psw generated by APP\r\n0: not changed; 1: changed' AFTER `updated_at`,
    ADD `first_time_login` TINYINT NOT NULL DEFAULT '1' COMMENT '0: no; 1: yes' AFTER `psw_changed`;