<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '
 All cars names from the NEXUS list are CORRECT' => '',
    '
 List of NEXUS cars not found in our DB' => '',
    ' in {daysCount} days' => '',
    ' today' => '',
    'ALL NOTIFICATION SENT' => '',
    'Car data: son_encod' => '',
    'Car documents without expiration date set' => '',
    'Car expired documents' => '',
    'Document expiration notification cron service is running...' => '',
    'Document expiration notification cron service is running...
' => '',
    'Documents expiration notification' => '',
    'Documents without expiration date notification cron service is running...
' => '',
    'EMAIL SENT' => '',
    'Expired documents notification cron service is running...
' => '',
    'For car <b>{plateNumber} no document was found</b>. Please verify!' => '',
    'For car <b>{plateNumber} no valid expiration date was set for any document</b>. Please verify!' => '',
    'For car <b>{plateNumber}</b> the <b>{docName}</b> is expired for <b>{daysCount} days</b>!' => '',
    'For car <b>{plateNumber}</b> the document <b>{docName} don\'t has a valid expiration date!</b>' => '',
    'For car {plateNumber} no valid expiration date was set for any document. Please verify!' => '',
    'For car {plateNumber} no valid expiration was set for {documentName}. Please verify!' => '',
    'Missing receivers emails' => '',
    'NEXUS - Cars notification' => '',
    'NEXUS - Locations notification' => '',
    'No id found for car. No processing will be done for this car.' => '',
    'No journeys received from Nexus. Please try again later, or contact them.' => '',
    'No journeys to import' => '',
    'No notification to send' => '',
    'Successfully sent the mail notification' => '',
    'The argument: "{params}" is not valid!' => '',
];
