<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'No relations found' => 'Nicio relație nu a fost găsită',
    'The data could not be saved' => 'Datele nu au putut fi salvate',
    'The permission day could not be saved' => 'Zilele de învoire nu au putut fi generate',
    'The working day could not be saved' => 'Zilele lucrătoare nu au putut fi generate',
    'The working day empl could not be saved' => 'Zilele de concediu nu au putut fi generate',
    'Do not forget to stop your shift.' => 'Nu uita să îți oprești tura.',
    'Do not forget to start your shift.' => 'Nu uita să îți începi tura.',
    'Do not forget to stop your break.' => 'Nu uita să îți oprești pauza.',
    'Firebase token is not set.' => 'Token-ul firebase nu este setat.',
    'Notifications are disabled.' => 'Notificările sunt dezactivate.',
    'Insufficient information.' => 'Informații insuficiente.'
];
