<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added' => 'Adăugat',
    'Added By' => 'Adăugat de',
    'All Day' => 'Toată ziua',
    'All reservations where successfully deleted' => 'Toate rezervările au fost șterse cu succes',
    'Capacity' => 'Capacitate',
    'Card Bg Class' => 'Clasa card bg',
    'Card Btn Class' => 'Clasa card btn',
    'Check In' => 'Check In',
    'Check Out' => 'Check Out',
    'Common Identifier' => 'Identificator comun',
    'Company ID' => 'Id Companie',
    'Company Ids' => 'Id-uri companii',
    'Could not set Outlook details. Please contact an administrator!' => 'Nu s-au putut seta detaliile Outlook. Vă rugăm să contactați un administrator!',
    'Details' => 'Detalii',
    'Duration' => 'Durată',
    'Failed to create meeting recurrence. Please contact an administrator!' => '',
    'Failed to create meeting. One attender could not be added. Please contact an administrator!' => 'Nu s-a putut crea întâlnirea. Un participant nu a putut fi adăugat. Vă rugăm să contactați un administrator!',
    'Failed to create meeting. Please contact an administrator!' => 'Nu s-a putut crea întâlnirea. Vă rugăm să contactați un administrator!',
    'Failed to delete meeting recurrence. Please contact an administrator!' => 'Nu s-a putut șterge recurența întâlnirii. Vă rugăm să contactați un administrator!',
    'Failed to update meeting. New details could not be updated. Please contact an administrator!' => 'Nu s-a putut actualiza întâlnirea. Noile detalii nu au putut fi actualizate. Vă rugăm să contactați un administrator!',
    'Failed to update meeting. One attender could not be added. Please contact an administrator!' => 'Nu s-a putut actualiza întâlnirea. Un participant nu a putut fi adăugat. Vă rugăm să contactați un administrator!',
    'Failed to update meeting. Parent details could not be updated. Please contact an administrator!' => 'Nu s-a putut actualiza întâlnirea. Detaliile părintelui nu au putut fi actualizate. Vă rugăm să contactați un administrator!',
    'Failed to update meeting. Please contact an administrator!' => 'Nu s-a putut actualiza întâlnirea. Vă rugăm să contactați un administrator!',
    'Human Readable' => 'Human Readable',
    'ID' => 'Id',
    'Incomplete data received.' => 'Date primite sunt incomplete.',
    'Local reservations where successfully deleted, but we could not remove them from Outlook calendar.' => 'Rezervările din aplicație au fost șterse cu succes, dar nu le-am putut elimina din calendarul Outlook.',
    'Meeting Common Identifier' => 'Identificator comun al întâlnire',
    'Meeting Details Icon Class' => 'Clasă icon detalii întâlnire',
    'Meeting ID' => 'Id întâlnire',
    'Name' => 'Nume',
    'No meeting rooms found. Please ask your system administrator to add at least one meeting room.' => 'Nu s-au găsit săli de întâlnire. Vă rugăm să cereți administratorului dvs. de sistem să adauge cel puțin o sală de întâlnire.',
    'No valid changes received' => 'Nu s-au primit modificări valide',
    'Outlook ID' => 'Outlook Id',
    'Page Class' => 'Clasă pagină',
    'Parent ID' => 'Parent Id',
    'Please beware, because no Outlook/Teams calendar event removed!' => 'Vă rugăm să aveți grijă, deoarece nu a fost eliminat niciun eveniment din calendarul Outlook/Teams!',
    'Recurrence Count' => 'Număr de recurențe',
    'Recurrence Date' => 'Data recurenței',
    'Recurrence Frequency' => 'Frecvența recurenței',
    'Recurrence Interval' => 'Interval de recurență',
    'Recurrence Type' => 'Tip de recurență',
    'Recurrence Weekday' => 'Ziua săptămânii recurentă',
    'Recurrent From' => 'Recurentă din',
    'Recurrent Until' => 'Recurentă până',
    'Recurring' => 'Recurente',
    'Reservation successfully deleted' => 'Rezervarea a fost ștearsă cu succes',
    'Reservation successfully deleted, but we could not remove her from Outlook calendar.' => 'Rezervarea a fost ștearsă, dar nu am putut-o elimina din calendarul Outlook.',
    'Rfc String' => 'String RFC',
    'Room ID' => 'Id cameră',
    'Sorry for inconvenience but, the reservation that you are trying to delete is added before Outlook calendar implementation and, for that reason, the option to remove single occurrence is not available. Please remove meeting series and add her again to align meeting details to new implementation.' => 'Ne pare rău pentru inconvenient, dar rezervarea pe care încercați să o ștergeți este adăugată înainte de implementarea calendarului Outlook și, din acest motiv, opțiunea de a elimina o singură apariție nu este disponibilă. Eliminați seria de întâlniri și adăugați-o din nou pentru a alinia detaliile întâlnirii la noua implementare.',
    'Sorry, you are not assigned to any company. Please contact an administrator to fix this!' => 'Ne pare rău, nu sunteți repartizat la nicio companie. Vă rugăm să contactați un administrator pentru a remedia acest lucru!',
    'Successfully retrieved meeting details' => 'Detaliile întâlnirii au fost preluate',
    'Successfully retrieved users list' => 'Lista de utilizatori a fost preluată cu succes',
    'Successfully saved the meeting details' => 'Detaliile întâlnirii au fost salvate cu succes',
    'Successfully sent the meeting room details' => 'S-au trimis cu succes detaliile sălii de ședințe',
    'Successfully sent the meeting rooms list' => 'S-au trimis cu succes lista sălilor de întâlnire',
    'Successfully updated all the meeting details' => 'Toate detaliile întâlnirii au fost actualizate cu succes',
    'The meeting could not be found' => 'Întâlnirea nu a putut fi găsită',
    'The meeting was successfully deleted' => 'Întâlnirea a fost ștearsă cu succes',
    'The new recurrence has no ending date' => 'Noua recurență nu are o dată de încheiere',
    'The received data are incomplete' => 'Datele primite sunt incomplete',
    'The received meeting details are wrong' => 'Detaliile întâlnirii primite sunt greșite',
    'The recurrence has no ending date' => 'Recurența nu are o dată de încheiere',
    'The reservation has no modifications compared with previous version' => 'Rezervarea nu are modificări față de versiunea anterioară',
    'Title' => 'Titlu',
    'Updated' => 'Actualizat',
    'Updated By' => ' Actualizat de',
    'User ID' => 'Id utilizator',
    'Your request could not be processed' => 'Solicitarea dvs. nu a putut fi procesată',
    'Your request could not be processed because old meeting data are wrong. Please contact an administrator!' => 'Solicitarea dvs. nu a putut fi procesată deoarece datele vechi ale întâlnirilor sunt greșite. Vă rugăm să contactați un administrator!',
    'Your update request could not be processed' => 'Solicitarea dvs. de actualizare nu a putut fi procesată',
];
