<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added' => '',
    'Added By' => '',
    'Cannot set two scopes for a journey' => '',
    'CC emails are not valid' => 'Emailurile CC nu sunt valide',
    'Code' => '',
    'Company ID' => '',
    'Could not register, your device not exist.' => '',
    'Could not update user data. Please contact an administrator' => '',
    'Deleted' => '',
    'Description' => '',
    'Domain ID' => '',
    'Employee ID' => '',
    'Entity ID' => '',
    'Emails are not valid' => 'Adresele de email nu sunt valide',
    "Email was sent to {email}" => "Emailul a fost trimis pentru {email}",
    "Email was sent to cc {email}" => "Emailul cc a fost trimis pentru {email}",
    'Failed to delete the journey id {id}, rest of journeys were deleted' => '',
    'Failed to update the journey id {id}, rest of journeys were updated' => '',
    'Family' => 'Familie',
    'Family category' => 'Categorie familie',
    'Family Placement' => 'Plasament în familie',
    'Family Name' => 'Nume familie',
    'Family Import' => 'Import familie',
    'File Hash' => 'Hash fișier',
    'File Path' => '',
    'File Name' => 'Nume fișier',
    'Friday' => '',
    'ID' => '',
    'Incomplete or invalid journey data' => '',
    'Interest is not set' => '',
    'Item ID' => '',
    'Item Type' => 'Tip articol',
    'Monday' => '',
    'Name' => '',
    'No accessory available.' => '',
    'No car id received' => '',
    'No data received' => 'Nu s-au preluat datele',
    'No emails receipt' => 'Nu s-au preluat adresele de e-mail',
    'No subject receipt' => 'Nu s-a preluat subiectul',
    'No content receipt' => 'Nu s-a preluat conținutul',
    'No attachments' => 'Nu există atașamente',
    'No journeys found' => '',
    'No kilometers received' => '',
    'No product type received.' => '',
    'No product version received.' => '',
    'No valid response received from server. Please contact an administrator' => '',
    'Project' => 'Proiect',
    'Success send emails' => 'Email-urile au fost trimise cu succes',
    'Saturday' => '',
    'Speciality' => 'Specialitate',
    'Source' => '',
    'Some error occurred while uploading the document, document is missing, please try again' => 'A apărut o eroare la încărcarea documentului, documentul lipsește, vă rugăm să încercați din nou',
    'Subdomain ID' => '',
    'Successfully authenticated' => '',
    'Successfully authenticated your device' => '',
    'Successfully deleted the journeys but some errors occurred' => '',
    'Successfully deleted' => '',
    'Successfully downloaded the document' => '',
    'Successfully registered your device' => '',
    'Successfully retrieved user details' => '',
    'Successfully sent the accessories list' => '',
    'Successfully sent the download details' => '',
    'Successfully sent the journeys list' => '',
    'Successfully sent the product version' => '',
    'Successfully updated the journeys' => '',
    'Successfully updated the journeys but some errors occurred' => '',
    'Successfully updated your keep alive status' => '',
    'Sunday' => '',
    'The document is too large, please try again with a smaller document' => 'Documentul este prea mare, vă rugăm să încercați din nou cu un document mai mic',
    'Type' => 'Tip',
    'Thursday' => '',
    'Tuesday' => '',
    'Unable to retrieve product version. Please contact an administrator' => '',
    'Updated' => '',
    'Updated By' => '',
    'Wednesday' => '',
    'Width' => 'Lăţime',
    'Wrong authentication data received' => '',
    'Wrong request received. No email or password received' => '',
    '{file} is not found' => '{file} nu este găsit'
];
