<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added' => 'Adăugat',
    'Added By' => 'Adăugat de',
    'Answer' => 'Răspuns',
    'BeMaria answer could not be saved and we don\'t have any validation errors' => 'Răspunsul de la BeMaria nu a putut fi salvat și nu avem erori de validare',
    'BeMaria did not receive any questions. Do you have a question for her?' => 'BeMaria nu a primit nicio întrebare. Ai o întrebare pentru ea?',
    'BeMaria did not receive question id.' => 'BeMaria nu a primit id-ul întrebării.',
    'BeMaria did not receive text.' => 'BeMaria nu a primit textul rostit',
    'BeMaria did not receive the written text' => 'BeMaria nu a primit textul scris',
    'BeMaria did not receive type.' => 'BeMaria nu a primit tipul.',
    'BeMaria feedback could not be saved and we don\'t have any validation errors' => 'Feedback-ul BeMaria nu a putut fi salvat și nu avem erori de validare',
    'BeMaria has an answer for you' => 'BeMaria are un răspuns pentru tine',
    'BeMaria model could not be updated with curl error details and we don\'t have any validation errors' => 'Modelul BeMaria nu a putut fi actualizat cu detalii despre erorile de curl și nu avem erori de validare',
    'BeMaria question could not be saved and we don\'t have any validation errors' => 'Întrebarea pentru BeMaria nu a putut fi salvată și nu avem erori de validare',
    'BeMaria text could not be saved and we don\'t have any validation errors' => 'Textul rostit pentru BeMaria nu a putut fi salvată și nu avem erori de validare',
    'Deleted' => 'Șters',
    'Device ID' => 'Dispozitiv',
    'Failed to save feedback. Please contact an administrator!' => 'Feedback-ul nu a fost salvat. Vă rugăm să contactați un administrator!',
    'Failed to save question. Please contact an administrator!' => 'Nu s-a putut salva întrebarea. Vă rugăm să contactați un administrator!',
    'Failed to save text. Please contact an administrator!' => 'Nu s-a putut salva textul. Vă rugăm să contactați un administrator!',
    'Failed to send your question. Please contact an administrator!' => 'Întrebarea dvs. nu a fost trimisă. Vă rugăm să contactați un administrator!',
    'Failed to update your question. Please contact an administrator!' => 'Nu s-a putut actualiza întrebarea. Vă rugăm să contactați un administrator!',
    'Feedback' => 'Feedback',
    'Huston we have a problem!' => '',
    'ID' => 'ID',
    'Ip Address' => 'Adresa IP',
    'Observations' => 'Observații',
    'Question' => 'Întrebare',
    'Question ID' => 'Întrebare',
    'Status' => 'Status',
    'Text' => 'Text',
    'The answer has been successfully saved' => 'Răspunsul a fost salvat cu succes',
    'The text has been successfully saved' => 'Textul rostit a fost salvat cu succes',
    'The written text has been successfully saved' => 'Textul scris a fost salvat cu succes',
    'Type' => 'Tip',
    'Updated' => 'Modificat',
    'Updated By' => 'Modificat de',
];
