<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A number of {insertedRevitFamilies} revit families have been inserted and {updatedRevitFamilies} updated.' => '',
    'Added' => '',
    'Added By' => '',
    'Articles' => '',
    'Code' => '',
    'Column \'A\' does not contain the header \'name\'!' => '',
    'Column \'B\' does not contain the header \'type\'!' => '',
    'Deleted' => '',
    'Description' => '',
    'Equipment(Feature)' => '',
    'Excel File' => '',
    'Failed to create imported file details!' => '',
    'Family ID' => '',
    'File Hash' => '',
    'File Name' => '',
    'ID' => '',
    'Import Hash ID' => '',
    'Item ID' => '',
    'Item Type' => '',
    'Items Type' => '',
    'Name' => '',
    'Project ID' => '',
    'Revit Family Name ID' => '',
    'Revit Project ID' => '',
    'Rfa File Path' => '',
    'Source' => '',
    'Speciality ID' => '',
    'The Revit project was not found!' => '',
    'The file could not be saved to disk. Please contact an administrator!' => '',
    'The speciality was not found!' => '',
    'There are required columns that are not completed in row with number {row}!' => '',
    'This file was also imported by {added_by}, on {added}!' => '',
    'Type' => '',
    'Updated' => '',
    'Updated By' => '',
    'We have a POST request but the data could not be loaded. Please contact an administrator!' => '',
];
