<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Added' => 'Adăugat',
    'Added By' => 'Adăugat de',
    'All families imported are articles' => 'Toate familiile importate sunt articole',
    'All families imported are equipments' => 'Toate familiile importate sunt echipamente',
    'All families imported are features' => 'Toate familiile importate sunt dotări',
    'Architecture' => 'Arhitectură',
    'Bad method used for request' => 'Metodă greșită utilizată pentru cerere',
    'Builder File' => 'Fișier Builder',
    'Cannot create a zip file' => 'Nu se poate crea un fișier zip',
    'Cannot open a zip file' => 'Nu se poate deschide fișierul zip',
    'Code' => 'Cod',
    'Could not load the data' => 'Nu s-au putut încărca datele',
    'Could not get the family name!' => 'Nu s-a putut obține numele de familie!',
    'Could not get the family category!' => 'Nu am putut obține categoria familie!',
    'Description' => 'Descriere',
    'Deleted' => 'Șters',
    'Did not get project name or code' => 'Nu am primit numele sau codul proiectului',
    'Did not get the source' => 'Nu am primit sursa',
    'Did not get the file_path' => 'Nu am primit file_path',
    'Did not get the Monada project or Builder project' => 'Nu am primit Monada project sau Builder project',
    'ID' => 'Id',
    'Item Type' => 'Tip articol',
    'Item' => 'Articol',
    'Error received' => 'Eroare primită',
    'Family' => 'Familie',
    'Family category' => 'Categoria familiei',
    'Family Import' => 'Import familie',
    'Family Name' => 'Nume familie',
    'File Name' => 'Nume fișier',
    'File Hash' => 'Hash fișier',
    'File was not found' => 'Fișierul nu a fost găsit',
    "File can't be copied" => "Fișierul nu a putut fi copiat",
    'Families imported from ERP' => 'Familii importate din ERP',
    'Families imported from a REVIT template' => 'Familii importate din șablon REVIT',
    'Families imported from REVIT workspace' => 'Familii importate din spațiul de lucru REVIT',
    'HeavyElectrics' => 'Instalații Electrice (Curenți Tari)',
    'Name' => 'Nume',
    'Monada File' => 'Fișier Monada',
    'No data received' => 'Nu s-au preluat datele',
    'No file was uploaded' => 'Nu a fost încărcat niciun fișier',
    'One or mode revit families belongs to another specialty' => 'Una sau mai multe familii revit aparțin unei alte specialități',
    'Updated' => 'Modificat',
    'Updated By' => 'Modificat de',
    'Project' => 'Proiect',
    'Please contact an administrator!' => 'Vă rugăm să contactați administratorul!',
    'Revit Project' => 'Proiect revit',
    'Source' => 'Sursă',
    'Successfully sent the projects' => 'Proiectele au fost trimise cu succes',
    'Speciality' => 'Specialitate',
    'Type' => 'Tip',
    'This file was also imported by {added_by}, on {added}!' => 'Acest fișier a fost importat de {added_by}, în data de {added}!',
    'The directory for uploaded files could not be created.' => 'Directorul pentru fișierele încărcate nu a putut fi creat.',
    'The file could not be saved to disk. Please contact an administrator' => 'Fișierul nu a putut fi salvat pe disc. Vă rugăm să contactați administratorul',
    'The file does not contain any family!' => 'Fișierul nu conține nici o familie!',
    'The project already exist' => 'Proiectul există deja!',
    'Successfully created the project' => 'Proiectul a fost creat cu succes',
    'Successfully updated the project' => 'Proiectul a fost modificat cu succes',
    'Successfully sent the download details' => 'Detaliile pentru descărcare au fost trimise cu succes',
    'Width' => 'Lățime'
];
