<?php

namespace api\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $username
 * @property string|null $first_name
 * @property string|null $last_name
 * @property string $auth_key
 * @property string $password_hash
 * @property string|null $password_reset_token
 * @property string|null $verification_token
 * @property string $email
 * @property string|null $photo
 * @property string|null $last_auth
 * @property int $status 0 - deleted; 9 - inactive; 10 - active;
 * @property int $created_at
 * @property int $updated_at
 * @property int $psw_changed used to verify if the user changed the default psw generated by APP
 * 0: not changed; 1: changed
 * @property int $first_time_login 0: no; 1: yes
 */
class UserParent extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('ecf_adm_db');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'auth_key', 'password_hash', 'email', 'created_at', 'updated_at'], 'required'],
            [['last_auth'], 'safe'],
            [['status', 'created_at', 'updated_at', 'psw_changed', 'first_time_login'], 'integer'],
            [['username', 'password_hash', 'password_reset_token', 'verification_token', 'email', 'photo'], 'string', 'max' => 255],
            [['first_name', 'last_name'], 'string', 'max' => 64],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
            [['photo'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'username' => Yii::t('app', 'Username'),
            'first_name' => Yii::t('app', 'First Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'password_hash' => Yii::t('app', 'Password Hash'),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'verification_token' => Yii::t('app', 'Verification Token'),
            'email' => Yii::t('app', 'Email'),
            'photo' => Yii::t('app', 'Photo'),
            'last_auth' => Yii::t('app', 'Last Auth'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'psw_changed' => Yii::t('app', 'Psw Changed'),
            'first_time_login' => Yii::t('app', 'First Time Login'),
        ];
    }
}
